### PR TITLE
Updated request-validation version to 1.2.4

### PR DESCRIPTION
**Pull request by andralungu**
@cristianconstantin, @ddragosd ping.

### CODE REVIEW

**Comment by ddragosd** [comment]
@andralungu can you add a link to the release and the change list for ref?

**Comment by andralungu** [comment]
@ddragosd, this is the link to the release: https://github.com/adobe-apiplatform/api-gateway-request-validation/releases/tag/1.2.4

**Comment by andralungu** [comment]
The lines containing `ONBUILD` were removed since they were interfering with the creation of a new docker image.

**Comment by cristianconstantin** [comment]
👍 for removing the `ONBUILD` instructions. 
@ddragosd what was the reason for adding them? Allowing to customize the initialization of the container? Unfortunately this would force you to duplicate the `init.sh` file.

**Comment by andralungu** [comment]
PR updated to allow customization of the basic configs.

**Comment by cristianconstantin** [comment]
@ddascal friendly ping

**Comment by cristianconstantin** [comment]
@ddascal friendly ping

**Review by cristianconstantin — APPROVED** [review]

**Comment by ddragosd** [comment]
:+1:

**Pull request merged**
