### PR TITLE
Fix/marathon logging

### PR DESCRIPTION
**Pull request by corinapurcarea**
Deleting unused file.

TBD: must update the documentation in order to remove all marathon references.

### CODE REVIEW

**Review by tudormaftei — APPROVED** [review]
👍

**Review by ddragosd — CHANGES_REQUESTED** [review]
This is a breaking change and this is still used by a few projects. Can we discuss first the motivation for removing it ?

**Review by atrifan — CHANGES_REQUESTED** [review]
this is an opensource project you don't know who is using this. Please remove it in the build process if you don't needed internaly

**Comment by corinapurcarea** [comment]
This is a temporary change that it's present, for the moment, only in the branch that we're using in building the docker image. There is a follow up story for the next sprint, for including in the gateway image just the necessary files from this repo(and implicitly adding back this file).

**Review by atrifan — APPROVED** [review]

**Pull request merged**
