### PR TITLE
multiple changes

### PR DESCRIPTION
**Pull request by jkt628**
- git submodules
- modern alpine and golang
- slim container
- sync generated subdir only

### CODE REVIEW

**Comment by ddragosd** [comment]
@jkt628 thanks for the submission. The title of this PR states correctly that there are multiple changes 😄  I'm wondering if it would be possible to split this one into smaller ones. Smaller, incremental changes are easier to review and take a shorter time to merge.
- I'm thinking we could very quickly expedite the last commit about updating to the latest [api-gateway-config-supervisor](https://github.com/adobe-apiplatform/api-gateway-config-supervisor/releases/tag/1.0.1-RC1) .
- Then we could have another PR for adding submodules to this repo and discuss it separately. 
- slim container could be another one. 
- sync'ing subfolders such as `generated-conf.d` could be another one. 

WDYT ?

**Comment by jkt628** [comment]
i apologize for the approach here; my intention was to get as quickly as possible to where @MikeWillCook and i are currently running.  i did invite debate on this approach via email and thought the response was generally positive.  unfortunately, the commits reflect the actual path i created to test the changes to api-gateway-config-supervisor within apigateway.  i can undo my work and redo it all again but i would absolutely rue the wasted time.  if you want individual PRs reflecting each change i can do that easily but the order will not be as you requested.  if this is an impediment to adoption i will start over, let me know.

**Comment by jkt628** [comment]
Merge remote-tracking branch 'upstream/master'

**Comment by rjmarsh** [comment]
Resubmit as individual PRs:

Required
- update the config-supervisor
- sync generated subdir only
- TCP

Optional
- git submodules (legal considerations because of libraries)
- slim container
- modern alpine and golang

**Pull request closed without merging**
